
gen:
	buf generate

run-web:
	cd my-app && npm run dev

## mock golang server which is 99% autogenerated
gen-mock:
	buf generate --template buf.mock-go.gen.yaml

run-mock:
	cd mocks && go run ./cmd/mocks/main.go