<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import CreateExample from '$lib/rpc/CreateExample.svelte'
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<CreateExample/> <br>
