<script>
    // @ts-nocheck
    /* this file was generated by protoc-gen-svelte-rpc do not edit */
    import ExampleEdit from "$lib/tutorial/ExampleEdit.svelte";
    import ExampleView from "$lib/tutorial/ExampleView.svelte";
    import { Example } from "$lib/gen/example_pb";
    import { ExampleServiceClient } from "$lib/client/ExampleService";
    import { json } from "@sveltejs/kit";
    let request = new Example();
    let response = new Example();

    async function makeRequest() {
        //response = await ExampleServiceClient.createExample(request);
        console.log(request)
        let a = await fetch("/api/CreateExample", {
            method: "POST",
            body: request.toJsonString(),
            headers: {
                "content-type": "application/json",
                "Authorization": "AHHHHHHH"
            },
        });

        let jaySon = await a.json();
        response = response.fromJson(jaySon);
        //console.log(jaySon);
        console.log(response);
        //console.log(a.json)
        //response = response.fromJson(a.json())
    }
</script>

<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<h3>Request</h3>

<ExampleEdit message={request} /> <br />
<!--<button on:click={makeRequest}> Send Request</button> <br /> -->
<button on:click={makeRequest}> Send Request</button> <br />

<h3>Response</h3>
<ExampleView message={response} />
