<script>
    // @ts-nocheck
    /* this file was generated by protoc-gen-svelte-rpc do not edit */
    /*let headers = new Map();
    if (headers.size == 0) {
        headers.set("Authorization", "Bearer ...");
        headers.set("RemoveMe", "Bearer ...");
    }
    function NewKey() {
        headers.delete(key);
        console.log(headers);
        headers = headers;
    }*/

    const headers = new Headers();
    headers.set("Authorization", "Bearer AbCdEf123456");

    function removeKey(key) {
        headers.delete(key);
        console.log(headers);
        //headers = headers;
    }

</script>

{#each [...headers] as [key, value]}
    <br />
    <input class="headers-key" bind:value={key} />
    <input class="headers-value" bind:value={value} />
    <br />
    <div>
        {key}: {value}
    </div>
    <button on:click={() => removeKey(key)}> Remove from Headers</button> <br />
{/each}
