<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import GetExample from '$lib/rpc/GetExample.svelte'
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<GetExample/> <br>
