<script>
    // @ts-nocheck
    /* this file was generated by protoc-gen-svelte-rpc do not edit */
    let headers = [];

    if (headers.size == 0) {
        headers[0] = {
            key: "",
            value: "",
        };
        headers = headers;
    }
    function pushHeader() {
        headers = headers.concat({
            key: "",
            value: "",
        });
        headers = headers;
    }
    function removeHeader(index) {
        headers.splice(index, 1);
        headers = headers;
    }
</script>

<h4>Headers</h4>

{#each headers as item, index}
    Key
    <input class="headers-key" bind:value={item.key} />
    Value
    <input class="headers-value" bind:value={item.value} />
    <button on:click={() => removeHeader(index)}> Remove </button> <br />
{/each}

<button on:click={pushHeader}> Add new header</button><br />

<slot></slot>