<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import ExampleEdit from '$lib/tutorial/ExampleEdit.svelte'
import ExampleView from '$lib/tutorial/ExampleView.svelte'
import {Example} from "$lib/gen/example_pb"
import {ExampleServiceClient} from '$lib/client/ExampleService'
let request = new Example()
let response = new Example()

  async function makeRequest() {
    console.log(request)
    let apiRes = await fetch("/api/CreateExample", {
      method: "POST",
      body: request.toJsonString(),
      headers: {
        "content-type": "application/json",
      },
    });

    response = new Example().fromJson(await apiRes.json())
    console.log(response)
}
  
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<h3> Request</h3>
<ExampleEdit message={request}/> <br>
<button on:click={makeRequest}> Send Request</button> <br>
<h3> Response</h3>
<ExampleView message={response}/>
