<script>
  // @ts-nocheck
  /* this file was generated by protoc-gen-svelte-rpc do not edit */
  import ExampleEdit from "$lib/tutorial/ExampleEdit.svelte";
  import ExampleView from "$lib/tutorial/ExampleView.svelte";
  import { Example } from "$lib/gen/example_pb";
  import { ExampleServiceClient } from "$lib/client/ExampleService";
  let request = new Example();
  let response = new Example();

  async function makeRequest() {
    console.log(request);
    //response = await ExampleServiceClient.createExample(request);
    let apiRes = await fetch("/api/CreateExample", {
      method: "POST",
      body: request.toJsonString(), // todo see if format matters.
      headers: { // todo have this be some actual value
        "content-type": "application/json",
        Authorization: "AHHHHHHH",
      },
    });

    response = response.fromJson(await apiRes.json())
  }
</script>

<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<h3>Request</h3>
<ExampleEdit message={request} /> <br />
<button on:click={makeRequest}> Send Request</button> <br />
<h3>Response</h3>
<ExampleView message={response} />
