<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import ExtraEdit from '$lib/tutorial/ExtraEdit.svelte'
import ExtraView from '$lib/tutorial/ExtraView.svelte'
import {Extra} from "$lib/gen/example_pb"
import {ExampleServiceClient} from '$lib/client/ExampleService'
let request = new Extra()
let response = new Extra()

  async function makeRequest() {
    console.log(request)
    // response = await ExampleServiceClient.createExtra(request)
    let apiRes = await fetch("/api/CreateExtra", {
      method: "POST",
      body: request.toJsonString(),
      headers: {
        "content-type": "application/json",
      },
    });

    response = new Extra().fromJson(await apiRes.json())
    console.log(response)
}
  
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<h3> Request</h3>
<ExtraEdit message={request}/> <br>
<button on:click={makeRequest}> Send Request</button> <br>
<h3> Response</h3>
<ExtraView message={response}/>
