<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import GetExampleRequestEdit from '$lib/tutorial/GetExampleRequestEdit.svelte'
import ExampleView from '$lib/tutorial/ExampleView.svelte'
import {GetExampleRequest} from "$lib/gen/example_pb"
import {Example} from "$lib/gen/example_pb"
import {ExampleServiceClient} from '$lib/client/ExampleService'
let request = new GetExampleRequest()
let response = new Example()

  async function makeRequest() {
    console.log(request)
    response = await ExampleServiceClient.getExample(request)
}
  
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<h3> Request</h3>
<GetExampleRequestEdit message={request}/> <br>
<button on:click={makeRequest}> Send Request</button> <br>
<h3> Response</h3>
<ExampleView message={response}/>
