<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Colour} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
      message = new Colour ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<p class="message-colour"> message.colour : {message.colour} </p>



<p class="message-liked"> message.liked : {message.liked}  </p>


