<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Colour} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new Colour ()
}
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<label for="message-colour"> message.colour </label> <br>
<input class="message-colour" bind:value={message.colour} >
<br>

