<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Example} from "$lib/gen/example_pb"
import ExtraView from '$lib/tutorial/ExtraView.svelte'
import NestView from '$lib/tutorial/Example.NestView.svelte'
import ColourView from '$lib/tutorial/ColourView.svelte'
import OperatingSystemView from '$lib/tutorial/OperatingSystemView.svelte'
export let message;
if (message == null ) {
      message = new Example ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<ExtraView message={message.extra} />



<NestView message={message.nest} />



{#each message.colours as item}
         <ColourView message={item} />
         {/each}


<p class="message-birdNest"> message.birdNest : {message.birdNest} </p>



<OperatingSystemView message={message.os} />


{#if message.tree.case == "treeType"}
<p class="message-tree.value"> message.tree.value : {message.tree.value} </p>

{/if}
{#if message.tree.case == "bush"}
<p class="message-tree.value"> message.tree.value : {message.tree.value}  </p>

{/if}
