<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import ExtraEdit from '$lib/tutorial/ExtraEdit.svelte'
import NestEdit from '$lib/tutorial/Example.NestEdit.svelte'
import ColourEdit from '$lib/tutorial/ColourEdit.svelte'
import OperatingSystemEdit from '$lib/tutorial/OperatingSystemEdit.svelte'
import {Example} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new Example ()
}
function pushcoloursArray() {message.colours = message.colours.concat(undefined)}
function removecoloursArray(index) {message.colours.splice(index, 1); message.colours = message.colours}



    // any messages within oneof need to be initialized.
    function setuptreeOneof() {message.tree.value = undefined
    message.tree.case = treeview;          
    }
    let treeview;
    $: treeview, setuptreeOneof();
    
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<ExtraEdit bind:message={message.extra}  />



<NestEdit bind:message={message.nest}  />




                <br>
                <label for="message-colours"> message.colours </label> <br>

                {#each message.colours as item, key} 
                    <ColourEdit bind:message={item}  />

                    <button on:click={() => removecoloursArray(key)}> Remove from message.colours</button><br>
                {/each}
                <button on:click={pushcoloursArray}> Add new message.colours</button><br>
                


<label for="message-birdNest-select"> message.birdNest </label> <br>
<select class="message-birdNest-select" bind:value={message.birdNest} >
<option value="BIRD_NEST_UNDEFINED">BIRD_NEST_UNDEFINED</option>
<option value="BIRD_NEST_DESTROYED">BIRD_NEST_DESTROYED</option>
<option value="BIRD_NEST_BUILT">BIRD_NEST_BUILT</option>
</select><br>



<OperatingSystemEdit bind:message={message.os}  />


<label>

    use treeType for Example oneof ?
    <input type="radio" bind:group={treeview} value={"treeType"} /> <br>
    
    </label> 
{#if treeview == "treeType"}
<label for="message-tree.value"> message.tree.value </label> <br>
<input class="message-tree.value" bind:value={message.tree.value} >
<br>
{/if}
<label>

    use bush for Example oneof ?
    <input type="radio" bind:group={treeview} value={"bush"} /> <br>
    
    </label> 
{#if treeview == "bush"}
<label for="message-tree.value"> message.tree.value </label> <br>
<input class="message-tree.value" type=checkbox  bind:checked={message.tree.value} >
<br>
{/if}
