<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Example_Nest} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new Example_Nest ()
}
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<label for="message-info"> message.info </label> <br>
<input class="message-info" bind:value={message.info} >
<br>

