<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Example_Nest} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
      message = new Example_Nest ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<p class="message-info"> message.info : {message.info} </p>



<p class="message-active"> message.active : {message.active}  </p>




        {#each message.tagsCategory as item }
            <p class="message-tagsCategory"> message.tagsCategory : {item} </p>

        {/each}
        


<p class="message-clean"> message.clean : {message.clean} </p>


