<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Example_Nest} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new Example_Nest ()
}
function pushtagsCategoryArray() {message.tagsCategory = message.tagsCategory.concat(undefined)}
function removetagsCategoryArray(index) {message.tagsCategory.splice(index, 1); message.tagsCategory = message.tagsCategory}

</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<label for="message-info"> message.info </label> <br>
<input class="message-info" bind:value={message.info} >
<br>


<label for="message-active"> message.active </label> <br>
<input class="message-active" type=checkbox  bind:checked={message.active} >
<br>



        <br>
        <label for="message-tagsCategory"> message.tagsCategory </label> <br>

        {#each message.tagsCategory as item, key} 
            <input class="message-tagsCategory" bind:value={item} >
<br>
            <button on:click={() => removetagsCategoryArray(key)}> Remove from message.tagsCategory</button> <br>
        {/each}
        <button on:click={pushtagsCategoryArray}> Add new message.tagsCategory</button> <br>


<label for="message-clean-select"> message.clean </label> <br>
<select class="message-clean-select" bind:value={message.clean} >
<option value="CLEANLINESS_UNSPECIFIED">CLEANLINESS_UNSPECIFIED</option>
<option value="CLEANLINESS_DISGUSTING">CLEANLINESS_DISGUSTING</option>
<option value="CLEANLINESS_BAD">CLEANLINESS_BAD</option>
<option value="CLEANLINESS_GOOD">CLEANLINESS_GOOD</option>
<option value="CLEANLINESS_EXCELLENT">CLEANLINESS_EXCELLENT</option>
</select><br>


