<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Extra} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new Extra ()
}
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<label for="message-more"> message.more </label> <br>
<input class="message-more" bind:value={message.more} >
<br>


<label for="message-count"> message.count </label> <br>
<input class="message-count" type=number bind:value={message.count} min=0 step="1" >
<br>

