<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {Extra} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
      message = new Extra ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<p class="message-more"> message.more : {message.more} </p>



<p class="message-count"> message.count : {message.count} </p>


