<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {GetExampleRequest} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
      message = new GetExampleRequest ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<p class="message-name"> message.name : {message.name} </p>


