<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {OperatingSystem_LinuxInfo} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
      message = new OperatingSystem_LinuxInfo ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->

<p class="message-distro"> message.distro : {message.distro} </p>



<p class="message-arch"> message.arch : {message.arch}  </p>


