<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import LinuxInfoEdit from '$lib/tutorial/OperatingSystem.LinuxInfoEdit.svelte'
import {OperatingSystem} from "$lib/gen/example_pb"
export let message;
if (message == null ) {
    message = new OperatingSystem ()
}
import {OperatingSystem_LinuxInfo} from "$lib/gen/example_pb"


    // any messages within oneof need to be initialized.
    function setupoperating_systemOneof() {
    // message = new OperatingSystem();
    switch (operating_systemview) {
        case "linuxInfo":
            message.operatingSystem.value = new OperatingSystem_LinuxInfo();
            break;
        default:}
    message.operatingSystem.case = operating_systemview;          
    }
    let operating_systemview;
    $: operating_systemview, setupoperating_systemOneof();
    
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<label>

    use windowsVersion for OperatingSystem oneof ?
    <input type="radio" bind:group={operating_systemview} value={"windowsVersion"} /> <br>
    
    </label> 
{#if operating_systemview == "windowsVersion"}
<label for="message-operatingSystem.value"> message.operatingSystem.value </label> <br>
<input class="message-operatingSystem.value" type=number bind:value={message.operatingSystem.value} min=0 step="1" >
<br>
{/if}
<label>

    use macVersion for OperatingSystem oneof ?
    <input type="radio" bind:group={operating_systemview} value={"macVersion"} /> <br>
    
    </label> 
{#if operating_systemview == "macVersion"}
<label for="message-operatingSystem.value"> message.operatingSystem.value </label> <br>
<input class="message-operatingSystem.value" bind:value={message.operatingSystem.value} >
<br>
{/if}
<label>

    use linuxInfo for OperatingSystem oneof ?
    <input type="radio" bind:group={operating_systemview} value={"linuxInfo"} /> <br>
    
    </label> 
{#if operating_systemview == "linuxInfo"}
<LinuxInfoEdit bind:message={message.operatingSystem.value}  />

{/if}
