<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import {OperatingSystem} from "$lib/gen/example_pb"
import LinuxInfoView from '$lib/tutorial/OperatingSystem.LinuxInfoView.svelte'
export let message;
if (message == null ) {
      message = new OperatingSystem ()
  }
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
{#if message.operatingSystem.case == "windowsVersion"}
<p class="message-operatingSystem.value"> message.operatingSystem.value : {message.operatingSystem.value} </p>

{/if}
{#if message.operatingSystem.case == "macVersion"}
<p class="message-operatingSystem.value"> message.operatingSystem.value : {message.operatingSystem.value} </p>

{/if}
{#if message.operatingSystem.case == "linuxInfo"}
<LinuxInfoView message={message.operatingSystem.value} />

{/if}
