<script> // @ts-nocheck
/* this file was generated by protoc-gen-svelte-rpc do not edit */
import CreateExtra from '$lib/rpc/CreateExtra.svelte'
</script>
<!-- this file was generated by protoc-gen-svelte-rpc do not edit-->
<CreateExtra/> <br>
